//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAndSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class clonebidon
    {
        public int id_bidon { get; set; }
        public Nullable<int> id_thongtinkhieunai { get; set; }
        public string bidon_tochuc_canhan { get; set; }
        public string hoten_canhan { get; set; }
        public string sohieu_cand { get; set; }
        public string nghe_nghiep { get; set; }
        public string capbac { get; set; }
        public string chucvu { get; set; }
        public string ten_coquandonvi { get; set; }
        public string diachi { get; set; }
        public string thuoc_lucluong { get; set; }
    }
}
