//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAndSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_donvi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_donvi()
        {
            this.tb_canbochiensy = new HashSet<tb_canbochiensy>();
            this.tb_thongtinkhieunai = new HashSet<tb_thongtinkhieunai>();
            this.tb_thongtintocao = new HashSet<tb_thongtintocao>();
        }
    
        public int ma_donvi { get; set; }
        public string ten_donvi { get; set; }
        public string kyhieu_donvi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_canbochiensy> tb_canbochiensy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_thongtinkhieunai> tb_thongtinkhieunai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_thongtintocao> tb_thongtintocao { get; set; }
    }
}
