//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAndSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_phanloai_tocao
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string ma_tocao { get; set; }
        public string phanloai_tocao { get; set; }
    }
}
