//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAndSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_status_sua_xoa_donthukhieunai
    {
        public int id_trangthai_donthukhieunai { get; set; }
        public Nullable<int> id_thongtinkhieunai { get; set; }
        public Nullable<int> status_sua_xoa { get; set; }
    
        public virtual tb_thongtinkhieunai tb_thongtinkhieunai { get; set; }
    }
}
