//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAndSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_temple_statuss
    {
        public int ID { get; set; }
        public Nullable<int> Finish { get; set; }
        public Nullable<int> Processing { get; set; }
        public Nullable<int> Out_of_date { get; set; }
        public Nullable<int> No_process { get; set; }
    }
}
