//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAndSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_temple_hinhthuc_xuly
    {
        public int ID { get; set; }
        public Nullable<int> Forward { get; set; }
        public Nullable<int> Direct_handling { get; set; }
        public Nullable<int> Untreated { get; set; }
    }
}
