//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAndSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_thongtintocao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_thongtintocao()
        {
            this.tb_bidon_tocao = new HashSet<tb_bidon_tocao>();
            this.tb_giaiquyettocao = new HashSet<tb_giaiquyettocao>();
            this.tb_nhatky_guidon_tocao = new HashSet<tb_nhatky_guidon_tocao>();
        }
    
        public int id_thongtintocao1 { get; set; }
        public string ma_donthu_tocao { get; set; }
        public Nullable<int> ma_canbo_nhapdulieu { get; set; }
        public Nullable<int> ma_donvi { get; set; }
        public Nullable<int> tochuc_canhan { get; set; }
        public Nullable<int> nacdanh_codanh { get; set; }
        public string hinhthuc_tocao { get; set; }
        public string tomtat_noidung { get; set; }
        public Nullable<int> dieukien_xuly_du_hoackhong { get; set; }
        public Nullable<int> giayto_tailieugoc_kemtheo { get; set; }
        public Nullable<int> tinhchat_vuviec_phuctap_dongian { get; set; }
        public string ma_tocao { get; set; }
        public Nullable<int> tocao_lienquanden_thamquyen_nhieucand_co_khong { get; set; }
        public Nullable<int> tocao_conoidung_khieunai { get; set; }
        public Nullable<int> tocao_nhieunoidung_linhvuc { get; set; }
        public string lydo_khongdu_dieukien { get; set; }
        public string xuly_tocao_khongthuoc_thamquyen { get; set; }
        public string chuyentocao_chodonvingoai { get; set; }
        public Nullable<int> duoc_nhanketqua { get; set; }
        public Nullable<int> duoc_baove { get; set; }
        public string yeucaukhac { get; set; }
        public string noigui { get; set; }
        public string tailieu_dinhkem { get; set; }
        public string ngaygio_nhap { get; set; }
        public string ngaygio_sua { get; set; }
        public Nullable<int> status_sua_xoa { get; set; }
        public Nullable<int> donvichuyenden { get; set; }
        public Nullable<int> ma_quatrinhgiaiquyet_donvichuyenden { get; set; }
        public string ten_canhan_tochuc { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string so_cmnd { get; set; }
        public Nullable<System.DateTime> ngaycap_cmnd { get; set; }
        public string noicap_cmnd { get; set; }
        public string dia_chi { get; set; }
        public string ten_cqdv_canhan { get; set; }
        public string nguoi_ky_trong_don { get; set; }
        public string ghi_chu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_bidon_tocao> tb_bidon_tocao { get; set; }
        public virtual tb_donvi tb_donvi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_giaiquyettocao> tb_giaiquyettocao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_nhatky_guidon_tocao> tb_nhatky_guidon_tocao { get; set; }
    }
}
