//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAndSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtintocao
    {
        public int id_thongtintocao1 { get; set; }
        public string ma_donthu_tocao { get; set; }
        public string ten_canhan_tochuc { get; set; }
        public string phanloai_tocao { get; set; }
        public Nullable<int> ma_donvi { get; set; }
    }
}
